/home/s0140/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/utils/dl_utils/setup_env.py:46: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
/home/s0140/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/utils/dl_utils/setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
Traceback (most recent call last):
  File "./train.py", line 116, in <module>
    main()
  File "./train.py", line 105, in main
    runner = Runner.from_cfg(cfg)
  File "/home/s0140/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/home/s0140/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 372, in __init__
    self.setup_env(env_cfg)
  File "/home/s0140/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 675, in setup_env
    init_dist(self.launcher, **dist_cfg)
  File "/home/s0140/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/dist/utils.py", line 85, in init_dist
    _init_dist_pytorch(backend, init_backend=init_backend, **kwargs)
  File "/home/s0140/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/dist/utils.py", line 130, in _init_dist_pytorch
    torch.cuda.set_device(local_rank)
  File "/home/s0140/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/cuda/__init__.py", line 313, in set_device
    torch._C._cuda_setDevice(device)
  File "/home/s0140/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/cuda/__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
/home/s0140/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 7728) of binary: /home/s0140/.conda/envs/openmmlab/bin/python3.8
Traceback (most recent call last):
  File "/home/s0140/.conda/envs/openmmlab/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/s0140/.conda/envs/openmmlab/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/s0140/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/s0140/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/s0140/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/s0140/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/s0140/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/s0140/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-09_15:21:13
  host      : tesla32
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 7728)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
